### ISSUE TITLE
Improvements: List Directories; NSZeroData on Create Directories; etc

### ISSUE THREAD

**Issue by FreekSanders** [AFNetworking/AFWebDAVManager#1]
Hello,
This is my first comment / commit to an open source project, so please direct me if this is the wrong outlet.
AFWebDAVManager is a great idea, however as the comment says, not yet production-ready. Thus, while testing I found a few bugs and fixed them. The updated code below should fix the following:
- contentsOfDirectoryAtURLString: better listing by changing the AFWebDAVMultiStatusResponse code
- createDirectoryAtURLString: if/else to handle the _NSZeroData response I get
- update namespacesKeyedByAbbreviation from "DAV" to "DAV:" to correspond with the way OSX sends WebDAV messages.

Greetings,
Freek Sanders.

**Comment by mattt** [comment]
Hi @FreekSanders.

Thanks for your contribution. I really appreciate your decision to give back to this project.

The best way to share your work would be through a Pull Request. [Follow the steps in this guide](https://help.github.com/articles/using-pull-requests) to submit your code. Once you've done that, I can go ahead and review them, for inclusion into the code base. Thanks!

**Comment by FreekSanders** [comment]
Thanks for the pointers.
Just posted my first pull request :D
